### ISSUE TITLE
返回按键的可触发范围太小了，能否改大一点呢

### ISSUE THREAD

**Issue by LiaoYuqiangzz** [SiberiaDante/TitleLayout#1]
我觉得目前来说点击标题左边的按钮返回的时候，可触发的点击范围太小了，能否给左边的textview和文字加个layout布局来扩大返回的可点击范围呢？

**Comment by SiberiaDante** [comment]
考虑的是返回键为文字时一般是两个字，点击区域足够了，就没有考虑这一点，稍后我优化下；返回按钮为图片是可设置图片宽度或者左padding

**Comment by SiberiaDante** [comment]
你可以先使用d_left_text_padding_start增加返回键为文字时的区域
